import type { Asset } from './schema';

/**
 * Single asset manifest. Every image or video shown on the site is declared
 * here once, with its real pixel dimensions and provenance; content files
 * refer to assets by id. `pnpm content:check` verifies each entry against
 * the file on disk and reports where it is used.
 */

const PLACEHOLDER = {
	source: 'generated-placeholder',
	permission:
		'Original placeholder generated by scripts/generate-placeholders.mjs for the preview. Replace before launch.',
} as const;

const cover = (slug: string, alt: string): Asset => ({
	src: `/media/projects/${slug}/cover.jpg`,
	type: 'image',
	mime: 'image/jpeg',
	width: 2400,
	height: 1800,
	alt,
	...PLACEHOLDER,
});

const social = (slug: string): Asset => ({
	src: `/media/projects/${slug}/social.jpg`,
	type: 'image',
	mime: 'image/jpeg',
	width: 1200,
	height: 630,
	alt: '',
	...PLACEHOLDER,
});

const SIZE = { wide: [2400, 1350], portrait: [1600, 2000], square: [1800, 1800] } as const;

const gallery = (slug: string, n: number, size: keyof typeof SIZE, alt: string): Asset => ({
	src: `/media/projects/${slug}/gallery-${String(n).padStart(2, '0')}.jpg`,
	type: 'image',
	mime: 'image/jpeg',
	width: SIZE[size][0],
	height: SIZE[size][1],
	alt,
	...PLACEHOLDER,
});

export const assets = {
	'portrait-placeholder': {
		src: '/media/portrait/placeholder.svg',
		type: 'image',
		mime: 'image/svg+xml',
		width: 1200,
		height: 1500,
		alt: '',
		...PLACEHOLDER,
	},

	'monolith-posters/cover': cover(
		'monolith-posters',
		'Three tall sample posters in charcoal, white and blue with simple geometric shapes',
	),
	'monolith-posters/social': social('monolith-posters'),
	'monolith-posters/g1': gallery(
		'monolith-posters',
		1,
		'wide',
		'Large white and blue lettering on a charcoal sample poster',
	),
	'monolith-posters/g2': gallery(
		'monolith-posters',
		2,
		'portrait',
		'Blue sample poster with a white arch shape',
	),
	'monolith-posters/g3': gallery(
		'monolith-posters',
		3,
		'square',
		'Alternating blue and charcoal vertical bars on a warm gray background',
	),

	'soft-matter/cover': cover(
		'soft-matter',
		'Three glossy sample spheres in orange, blue and gray on a lilac background',
	),
	'soft-matter/social': social('soft-matter'),
	'soft-matter/g1': gallery(
		'soft-matter',
		1,
		'wide',
		'A single blue sphere lit from the top left on a dark background',
	),
	'soft-matter/g2': gallery(
		'soft-matter',
		2,
		'square',
		'White and orange spheres resting on a light surface',
	),
	'soft-matter/g3': gallery('soft-matter', 3, 'portrait', 'A blue sphere stacked in front of a gray sphere'),
	'soft-matter/loop-poster': {
		src: '/media/projects/soft-matter/loop-poster.jpg',
		type: 'image',
		mime: 'image/jpeg',
		width: 1280,
		height: 720,
		alt: 'First frame of the sample loop: a blue sphere with a small orange sphere beside it',
		...PLACEHOLDER,
	},
	'soft-matter/loop': {
		src: '/media/projects/soft-matter/loop.mp4',
		type: 'video',
		mime: 'video/mp4',
		width: 1280,
		height: 720,
		alt: 'Four-second silent loop: a small orange sphere orbits a gently bobbing blue sphere',
		alternates: [{ src: '/media/projects/soft-matter/loop.webm', mime: 'video/webm' }],
		poster: 'soft-matter/loop-poster',
		...PLACEHOLDER,
	},

	'night-market-identity/cover': cover(
		'night-market-identity',
		'Sample identity: a yellow crescent mark beside the words Night Market on black',
	),
	'night-market-identity/social': social('night-market-identity'),
	'night-market-identity/g1': gallery(
		'night-market-identity',
		1,
		'wide',
		'Four colour swatches: yellow, orange, blue and near-black, each labelled with its hex value',
	),
	'night-market-identity/g2': gallery(
		'night-market-identity',
		2,
		'portrait',
		'Orange sample poster reading Open after dark with a yellow circle',
	),
	'night-market-identity/g3': gallery(
		'night-market-identity',
		3,
		'square',
		'Black crescent mark above the words Night Market on white',
	),

	'orbit-objects/cover': cover(
		'orbit-objects',
		'Sample 3D still life: a blue ring, a pale cylinder and a dark sphere on gray',
	),
	'orbit-objects/social': social('orbit-objects'),
	'orbit-objects/g1': gallery(
		'orbit-objects',
		1,
		'wide',
		'A dark ring shape centred on a light gray background',
	),
	'orbit-objects/g2': gallery('orbit-objects', 2, 'square', 'A pale cylinder on a blue background'),
	'orbit-objects/g3': gallery(
		'orbit-objects',
		3,
		'wide',
		'Four small spheres in blue, orange, gray and yellow in a row on black',
	),

	'paper-architecture/cover': cover(
		'paper-architecture',
		'Sample layered paper shapes stepping from white to blue on a cream background',
	),
	'paper-architecture/social': social('paper-architecture'),
	'paper-architecture/g1': gallery(
		'paper-architecture',
		1,
		'portrait',
		'Stacked arch-shaped paper layers fading from white to blue',
	),
	'paper-architecture/g2': gallery(
		'paper-architecture',
		2,
		'wide',
		'Rising paper bars on black, the tallest in blue',
	),

	'signal-type/cover': cover('signal-type', 'The word Signal repeated in rows of increasing weight on blue'),
	'signal-type/social': social('signal-type'),
	'signal-type/g1': gallery('signal-type', 1, 'square', 'Large blue letters S and g on white'),
	'signal-type/g2': gallery(
		'signal-type',
		2,
		'wide',
		'A row of letter S shapes from thin to heavy on black, one in blue',
	),
} satisfies Record<string, Asset>;

export type AssetId = keyof typeof assets;

export function getAsset(id: string): Asset {
	const asset = (assets as Record<string, Asset>)[id];
	if (!asset) throw new Error(`Unknown asset id "${id}"`);
	return asset;
}
