/**
 * Content and launch validation for the CMS content in content/.
 *
 *   pnpm content:check     structural checks; safe for preview builds
 *   pnpm check:launch      also fails on anything that must not go public
 *                          (placeholders, samples, missing origin, contact setup)
 *
 * Also regenerates docs/asset-manifest.md.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { loadContent, PLACEHOLDER_NAME } from '../src/content/load';
import { parseSiteOrigin } from '../src/lib/config';

const launch = process.argv.includes('--launch');
const root = resolve(import.meta.dirname, '..');
const { site, projects, errors: contentErrors, warnings: contentWarnings, files } = loadContent(root);
const errors = contentErrors.map((i) => `${i.path}: ${i.message}`);
const warnings = contentWarnings.map((i) => `${i.path}: ${i.message}`);

// Files in public/media that nothing references (the portrait placeholder is a code fallback).
const used = new Set([...files.map((f) => f.src), '/media/portrait/placeholder.svg']);
const walk = (dir: string): string[] =>
	readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
		e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
	);
for (const file of walk(join(root, 'public', 'media'))) {
	const src = `/${relative(join(root, 'public'), file)}`;
	if (!used.has(src) && !src.endsWith('/social.jpg'))
		warnings.push(`public${src} is not used by any content`);
}

if (launch) {
	if (site.name === PLACEHOLDER_NAME) errors.push('Site identity: the name is still the placeholder');
	if (!site.portrait)
		errors.push('Site identity: no portrait uploaded (placeholder silhouette would be shown)');
	if (site.bio.some((b) => /placeholder/i.test(b)))
		errors.push('Site identity: bio still contains placeholder text');
	const samples = projects.filter((p) => p.publishStatus === 'sample');
	if (samples.length)
		errors.push(
			`${samples.length} sample project(s) still routable: ${samples.map((p) => p.slug).join(', ')}`,
		);
	if (!projects.some((p) => p.publishStatus === 'published')) errors.push('No published projects');

	const origin = parseSiteOrigin(process.env.SITE_URL);
	if (!origin) errors.push('SITE_URL is missing or not a valid https origin');
	else if (origin.isLocal) errors.push('SITE_URL points to a local host');
	if (process.env.SITE_INDEXING !== 'allow')
		errors.push('SITE_INDEXING is not "allow" (site would stay noindex)');

	const contactReady = Boolean(
		process.env.RESEND_API_KEY && process.env.CONTACT_TO_EMAIL && process.env.CONTACT_FROM_EMAIL,
	);
	if (!contactReady && !site.email)
		errors.push('No way to be contacted: configure the contact form provider or add a public email');
	if (!contactReady)
		warnings.push('Contact form provider not configured; the form will show its unconfigured state');
	if (contactReady && !(process.env.UPSTASH_REDIS_REST_URL && process.env.UPSTASH_REDIS_REST_TOKEN)) {
		warnings.push(
			'Rate limiting falls back to per-instance memory; configure Upstash for serverless/multi-instance hosting',
		);
	}
	if (process.env.NEXT_PUBLIC_KEYSTATIC_STORAGE !== 'github') {
		warnings.push(
			'CMS is in local mode: /keystatic will be disabled in production (see docs/cms.md for GitHub mode)',
		);
	}
}

const rows = files.map(
	(f) =>
		`| \`public${f.src}\` | ${f.kind} | ${f.width ? `${f.width}×${f.height}` : '—'} | ${f.source} | ${f.usedIn} |`,
);
writeFileSync(
	join(root, 'docs', 'asset-manifest.md'),
	`# Asset manifest\n\nGenerated by \`pnpm content:check\` from the CMS content in \`content/\` (sizes read from the files). Do not edit by hand.\n\n| File | Type | Size | Source | Used in |\n| --- | --- | --- | --- | --- |\n${rows.join('\n')}\n`,
);

warnings.forEach((w) => console.warn(`⚠ ${w}`));
errors.forEach((e) => console.error(`✗ ${e}`));
console.log(
	`${launch ? 'Launch' : 'Content'} check: ${projects.length} projects, ${files.length} media files, ${errors.length} error(s), ${warnings.length} warning(s).`,
);
process.exit(errors.length ? 1 : 0);
